### ISSUE TITLE
Здравей питане отностно проблема който си разрешил

### ISSUE THREAD

**Issue by KristiyanVasilev96** [borisboev79/CGM-Project#1]
Имам същия проблем които беше задал на Лъчо с invalid username or password да те попитам как точно разреши проблема ,че сега погледнах и имам същия.

**Comment by borisboev79** [comment]
Здрасти, за кой проблем става дума?

**Comment by KristiyanVasilev96** [comment]
Здрасти, беше писал преди време на Лъчо отностно проблема при логин формата когато се опитваш да се логнеш с несъществуващ юзър не изкарваше грешката.

**Comment by borisboev79** [comment]
За съжаление нямам никакъв спомен. То толкова проблеми ми минаха оттогава през главата с тоя проект :)
